### ISSUE TITLE
You have requested a non-existent service "jaxon.ajax"

### ISSUE THREAD

**Issue by nevtag** [jaxon-php/jaxon-symfony#3]
Hi Thierry,
when did you try the last time to install jaxon-php in a fresh installation of symfony?
Your installation path and the settings in the configuration files are not equal, for beginners who will test jaxon-php with symfony is that frustrating.
For me it's a good occasion to learn how symfony works.
regards, Joc

**Comment by feuzeu** [comment]
Hi Joc,
The Jaxon automatically exports all classes in its class directory. Thus the ideal default value should be an empty an unused dir, which does not exist in a fresh symfony installation.
The alternative is to silently ignore the error when the class directory does not exist, but it can also be frustrating to have the library not working and no error message to tell why.

I've edited the README to state that the class directory must be manually created.

Regards,
Thierry

**Comment by nevtag** [comment]
Hi Thierry,
well that's right and I have created the directory /data/www/mysymfony/src/Jaxon/App, but the "Uncaught PHP Exception ....You have requested a non-existent service 'jaxon.ajax' " is still alive. I think, that has nothing to do with the directory, or I'm wrong?
If I make `php bin/console debug:container jaxon` jaxon.ajax is listed.
But If I call it, as shown in the example, I got the exception that the service is not existent.
Regards,
Joc

**Comment by feuzeu** [comment]
Hi Joc,

May be you need to flush the caches?
`php bin/console  cache:clear --env=prod`
`php bin/console  cache:clear --env=debug`

Thierry

**Comment by nevtag** [comment]
Hi Thierry,
I did it and get this error.
`request.CRITICAL: Uncaught PHP Exception Jaxon\Exception\Config\Yaml: "install" at /data/www/mysymfony/vendor/jaxon-php/jaxon-core/src/Config/Yaml.php line 33 {"exception":"[object] (Jaxon\\Exception\\Config\\Yaml(code: 0): install at /data/www/mysymfony/vendor/jaxon-php/jaxon-core/src/Config/Yaml.php:33)"} []`
Than I make a new clean installation only symfony latest one and jaxon-symfony. Create app-dir and edit the files. Chown to www-data over symfony dir, and than I call the page, and I get the same error.
Now I have installed symfony/yaml, but that was not the trick, same result.
I did it again, to exclude I made a mistake, but same result.
Have you an idea what it can be?

By the way, jaxon standalone works fine, and my plugin is working well.

Regards,
Joc

**Comment by feuzeu** [comment]
Hi Joc,
You need to install the php-yaml package on your system.
If you catch the error and print the corresponding message, you will have this explained.
For sure, this point is missing in the documentation.
Regards,
Thierry

**Comment by nevtag** [comment]
Hi Thierry,
I will test it.
But what I found is that you can use the symfony/yaml component. That works for me.

```
namespace Jaxon\Config;

class Yaml
{
    /**
     * Read and set Jaxon options from a YAML formatted config file
     *
     * @param array         $sConfigFile        The full path to the config file
     * @param string        $sKeys              The keys of the options in the file
     *
     * @return array
     */
    public static function read($sConfigFile, $sKeys = '')
    {
        $sConfigFile = realpath($sConfigFile);
#        if(!extension_loaded('yaml'))
#        {
#            throw new \Jaxon\Exception\Config\Yaml('install');
#        }
        if(!is_readable($sConfigFile))
        {
            throw new \Jaxon\Exception\Config\File('access', $sConfigFile);
        }
#        $aConfigOptions = yaml_parse_file($sConfigFile);
        $aConfigOptions = \Symfony\Component\Yaml\Yaml::parse(file_get_contents($sConfigFile));
        if(!is_array($aConfigOptions))
        {
            throw new \Jaxon\Exception\Config\File('content', $sConfigFile);
        }

        // Setup the config options into the library.
        $jaxon = jaxon();
        $jaxon->setOptions($aConfigOptions, $sKeys);
        return $aConfigOptions;
    }
}

```

Regards,
Joc

**Comment by feuzeu** [comment]
Hi Joc,
Your fix works because you are already using Symfony. There's no requirement on the Symfony Yaml package in the Jaxon core library, so it will not work in certain cases.
Regards,
Thierry

**Comment by nevtag** [comment]
Hi Thierry,
that make sense and is interesting because my standalone installation works, I have only libyaml-0-2 on my system installed. The question is know, why does it work standalone, but not with symfony.
Regards,
Joc

**Comment by feuzeu** [comment]
The jaxon-symfony package loads it config options from a Yaml file. That's why it calls the yaml_parse_file() function, which is provided by the php-yaml package.
However, having the php-yaml package installed is not a requirement for the jaxon-core package where the config functions are implemented, since loading config from a Yaml file is a feature many users of the jaxon-core package do not need.

Thierry

**Comment by nevtag** [comment]
That did it!
Packages `libyaml libyaml-dev` are needed and PHP7 needs `pecl install yaml-2.0.0`.
Than a fresh installation of symfony with jaxon-php/jaxon-symfony is working well and `{{ jaxon_script |raw }}` is writing the right output in the header.
