### ISSUE TITLE
Symfony 4 Compatibilty

### ISSUE THREAD

**Issue by ITspirit** [jaxon-php/jaxon-symfony#6]
Would be great, if this package can be made compatible with symfony 4.

Not sure, but i think it´s enough to set the version in composer.json:

"symfony/symfony": "^3.4||^4.0"

**Comment by nevtag** [comment]
Not working with Version 4.3

**Comment by ITspirit** [comment]
Can you be a little more precise? Just saying "not working" is not a helpful feedback.

**Comment by nevtag** [comment]
You' re right ;-)

#composer update without "jaxon-php/jaxon-symfony": "~2.0"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Nothing to install or update
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [OK]
Executing script assets:install public [OK]

#composer update with "jaxon-php/jaxon-symfony": "~2.0"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/symfony v4.3.0 conflicts with __root__[dev-master].
    - symfony/symfony v4.3.1 conflicts with __root__[dev-master].
    - symfony/symfony v4.3.2 conflicts with __root__[dev-master].
    - symfony/symfony v4.3.3 conflicts with __root__[dev-master].
    - jaxon-php/jaxon-symfony v2.1.0 requires symfony/symfony 3.4.* -> no matching package found.
    - jaxon-php/jaxon-symfony v2.0.4 requires symfony/symfony 2.8.*|3.0.*|3.1.*|3.2.*|3.3.* -> no matching package found.
    - jaxon-php/jaxon-symfony v2.0.3 requires symfony/symfony 2.8.*|3.0.*|3.1.*|3.2.*|3.3.*|3.4.* -> no matching package found.
    - jaxon-php/jaxon-symfony v2.0.2 requires symfony/symfony 2.8.*|3.0.*|3.1.* -> no matching package found.
    - jaxon-php/jaxon-symfony v2.0.1 requires symfony/symfony 2.8.*|3.0.*|3.1.* -> no matching package found.
    - jaxon-php/jaxon-symfony v2.0.0 requires symfony/symfony 2.8.*|3.0.*|3.1.* -> no matching package found.
    - Installation request for __root__dev-master -> satisfiable by __root__[dev-master].
    - jaxon-php/jaxon-symfony v2.2.0 requires symfony/symfony ^3.4||^4.0 -> satisfiable by symfony/symfony[v4.3.0, v4.3.1, v4.3.2, v4.3.3].
    - Installation request for jaxon-php/jaxon-symfony ~2.0 -> satisfiable by jaxon-php/jaxon-symfony[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.1.0, v2.2.0].

**Comment by feuzeu** [comment]
Hi,

I've release the [3.2.0 tag](https://github.com/jaxon-php/jaxon-symfony/releases/tag/v3.2.0).
It now works with Symfony 4.* and 5.*.
